### ISSUE TITLE
Filters are not working in qute web views

### ISSUE THREAD

**Issue by kucharzyk** [quarkiverse/quarkus-qute-web#74]
I've created pretty standard filters for my application. They are working fine for standard rest easy endpoints but not for qute web views.

```java
import io.quarkus.logging.Log;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerResponseContext;
import jakarta.ws.rs.core.Request;
import org.jboss.resteasy.reactive.server.ServerRequestFilter;
import org.jboss.resteasy.reactive.server.ServerResponseFilter;

public class SampleFilters {

    @ServerRequestFilter(priority = Priorities.AUTHENTICATION)
    public void filterRequest(ContainerRequestContext requestContext, Request req) {
        Log.warn("request filter");
    }

    @ServerResponseFilter(priority = Priorities.AUTHENTICATION)
    public void filterResponse(ContainerResponseContext responseContext) {
        Log.warn("response filter");
    }


}
```

This filter is not invoked at all for any qute views. I was expecting they will behave like normal rest easy endpoints.

**Comment by mkouba** [comment]
Well, the `resteasy-reactive` filters are indeed not used for routes registered by `qute-web`. They're only applied to JAX-RS resources. You would need to register a filter in an [`@Observes io.quarkus.vertx.http.runtime.filters.Filters`](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/filters/Filters.java) method or a [`@RouteFilter`](https://quarkus.io/guides/reactive-routes#intercepting-http-requests) method (from the `reactive-routes` extension) in order to apply the same logic for any route (including the JAX-RS resources).

**Comment by mkouba** [comment]
I'm going to close this one because `quarkus-qute-web` is not built on top of `resteasy-reactive` or JAX-RS in general.
